config/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path,include
from django.views import defaults as default_views

from . import views

urlpatterns = [
    path('',views.welcome_to_inqoire,name='index'),
    path('account/',include('inqoire.account.urls',namespace='account')),
    path('comment/',include('inqoire.comment.urls',namespace='comment')),
    path('answer/',include('inqoire.answer.urls',namespace='answer')),
    path('question/',include('inqoire.question.urls',namespace='question')),
    path('users/',include('inqoire.users.urls',namespace='users')),
    path('vote/',include('inqoire.vote.urls',namespace='vote')),
    path('connection/',include('inqoire.connection.urls',namespace='connection')),
    path('admin/', admin.site.urls),# change url in production. `SECURITY` reasons.
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    
    # Test Dev. Error Pages
    urlpatterns += [
        path('400/', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        path('403/', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        path('404/', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        path('500/', default_views.server_error),
    ]

inqoire/account/urls.py
from django.urls import path

from . import views

app_name = 'account'

urlpatterns = [
	path('auth/register/',views.register,name='register'),
    path('auth/login/',views.login,name='login'),
    path('auth/logout/',views.logout,name='logout'),
    path('auth/verify-user-activation-code/<str:token>/',views.validate_confirmation_token,name='validate-token'),
    path('user/confirmation-reminder/<str:email>/',views.confirm_via_email,name='confirmation-reminder'),
    
]

inqoire/answer/urls.py
from django.urls import path

from . import views

app_name = 'answer'

urlpatterns = [
	path('add/',views.answer_add,name='answer-add'),
	path('view/<str:slug>/',views.answer_view,name='answer-view'),
]

inqoire/comment/urls.py
from django.urls import path
from .import views


app_name = 'comment'

urlpatterns = [
    path('add/',views.comment_post,name='comment-post'),
]

inqoire/vote/urls.py
from django.urls import path
from .import views


app_name = 'vote'

urlpatterns = [
    path('user-vote/',views.vote,name='user-vote'),
]

templates/partials/_nav.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-light bg-light shadow-sm fixed-top nav-page">
  <a class="navbar-brand" href="{% url 'index' %}">inQoire</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">

    <!-- Left Nav <ul> -->
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link active-link" href="{% url 'index' %}">Home</a>
      </li>
      <!--  <li class="nav-item">
        <a class="nav-link" href="#">Answer</a>
      </li> -->
      {% if is_auth %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'question:question-page' %}">Question</a>
      </li>
      {% endif %}
    </ul>

    <!-- Center Nav <ul> -->
    <ul class="nav justify-content-center">
       <li class="nav-item search-icon-span">
        <span class="nav-link"><i class="la la-search"></i></span>
       </li>
    </ul>

    {% if is_auth %}
    <!-- Right Nav <ul> -->
    <ul class="navbar-nav ml-auto">
       <li class="nav-item">
        <span class="nav-link"><i class="la la-comments"></i></span>
       </li>

       <li class="nav-item">
        <span class="nav-link"><i class="la la-bell"></i></span>
       </li>

	     <li class="nav-item dropdown dropleft">
          <!-- avatar -->
          <img src="{% if request.user.profile.pic %}{{request.user.profile.pic_url}}{% else %}{% static 'img/avatar.jpg' %}{% endif%}" class="nav-avatar-responsive dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"/>
          <!-- avatar -->
        <div class="dropdown-menu shadow-sm" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="{{ request.user.url }}">Profile</a>
          <a class="dropdown-item" href="#">Bookmarks</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="{% url 'account:logout' %}">Logout</a>
        </div>
      </li>

    </ul>
    {% else %}
    <!-- Right Nav <ul> -->
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'account:register' %}">SignUp</a>
      </li>
      <li class="nav-item">
        <a class="nav-link">or</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'account:login' %}">Login</a>
      </li>
    </ul>
    {% endif %}

  </div>
</nav>

templates/partials/auth_nav.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-light bg-light shadow-sm fixed-top nav-page">
  <a class="navbar-brand" href="{% url 'index' %}">inQoire</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">

    <!-- Left Nav <ul> -->
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'index' %}" style="margin-bottom: -4px;">Home</a>
      </li>
    </ul>

    {% if not is_auth %}
    <!-- Right Nav <ul> -->
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <a class="nav-link" href="#">Subscribe</a>
      </li>
    </ul>
    {% endif %}

  </div>
</nav>

templates/partials/follow_form.html
<form action="{% url 'connection:connection-switch' %}" method="POST" class="follow-form">
	{% csrf_token %}
	<input type="submit" class="btn btn-outline-primary follow-btn" value="Connect" name='follow_btn'/>
	<input type="hidden" name="from_user" value="{{request.user.username}}">
	<input type="hidden" name="to_user" value="{{user_obj.username}}">
</form>

templates/partials/message.html
<section class="container">
  <section class="row">
    <section class="col-lg-6 offset-lg-3 text-center" style="margin-top: 4em;">
            {% if messages %}
              {% for message in messages %}
                  <div class="alert alert-{{ message.tags }} fade in">
                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                    {{ message }}
                  </div>        
              {% endfor %}
          {% endif %}
    </section>
  </section>
</section>

templates/partials/question-answer-card.html
{% load static %}					
{% load crispy_forms_tags %}
					<!-- card starts here -->
					{% if questions %}
							{% for q in questions %}
								{% if is_auth %}
										<div class="card col-lg-12">
												 <div class="card-body">
												   	<form action="{% url 'answer:answer-add'%}" method="POST" class="answer-form" enctype="multipart/form-data">
												   		{% csrf_token %}
												   		{{answer_form|crispy}}
												   		<input type="hidden" name="question_id" value="{{q.id}}">
												   		<button class="btn btn-outline-primary link-btn">Send</button>
												   		<div class="lds-ellipsis"><div></div><div></div><div></div><div></div></div>
												   	</form>
												 </div>
										</div>
								{% endif %}
							<div class="card mb-4" style="width: -webkit-fill-available !important;"> 
								  	  <section class="card-header clear-fix">
								  	  	{% if q.most_upvote_answer.answer_by.profile.pic %}
								  	  	<img src="{{q.asked_by.profile.pic_url}}" alt="" class="avatar-qs" />
								  	  	{% else %}
								  	  	<img src="{% static 'img/avatar-1.png' %}" alt="" class="avatar-qs" />
								  	  	{% endif %}
								  	  	{% if q.text %}
									    <h5 class="card-title">
									    	<a href="{{q.qst_detail_url}}">{{q.text}}</a>
									    </h5>
									    {% endif %}
								  	  	<p>By <a href="{{q.asked_by.url}}">{{q.asked_by.full_name}}</a>
								  	  		{% if q.asked_by.profile.profession %}
								  	  		{{q.asked_by.profile.profession}}{% endif %}.
								  	  		<span class="answer-dt"> answered by 
								  	  			<a href="{{q.most_upvote_answer.answer_by.url}}">{{q.most_upvote_answer.answer_by}}</a>
								  	  		</span>
								  	  	</p>
								  	  	<br>
								  	  	<p class="question-answers-count"><a href="#">({{q.answers_count}})</a> Answer{{q.answers_count|pluralize}} provided for this question.</p>
									  </section>
									    <!-- <img src="{% static 'img/qf.jpeg' %}" class="card-img-top question-file" alt="..."> -->
									    <div class="card-body clear-fix	">
									      <i class="la la-check float-left"></i>
									      <p class="card-text">
									      	{% if q.most_upvote_answer.file %}
									      	<a href="{{q.most_upvote_answer.url}}">
										      		<img src="{{q.most_upvote_answer.file_url}}" alt="" class="answer-file-resp">
									        </a>
										    {% elif q.file_url %}
										    <a href="{{q.most_upvote_answer.url}}">
									      		<img src="{{q.file_url}}" alt="" class="answer-file-resp">
									      	</a>
									      	{% endif %}
									      	<p>
									      	<a href="{{q.most_upvote_answer.url}}" class="answer-link"class="answer-link">{{q.most_upvote_answer.text}}</a>
									        </p>
									      <!-- <button class="read-more-btn">Read More</button> -->
									      </p>
									    </div>
									    <div class="card-footer clear-fix">
									      <small class="text-muted qs-text">
									      {{q.most_upvote_answer.upvotes}} upvote{{q.most_upvote_answer.upvotes|pluralize}}
									  	  </small>
									      <small class="text-muted qs-text comment-small">
									      <span class="count-comment">{{q.most_upvote_answer.answer_comments_count}}</span> comment{{q.most_upvote_answer.answer_comments_count|pluralize}}
									      </small>
									      <!-- <small class="text-muted qs-text">4 shares</small> -->
									      <small class="text-muted qs-text">
									      {{q.most_upvote_answer.downvotes}} downvote{{q.most_upvote_answer.downvotes|pluralize}}
									  	 </small>
									      <small class="text-muted qs-text">{{q.most_upvote_answer.views}} view{{q.most_upvote_answer.views|pluralize}}</small>
									      <small class="text-muted float-right"><i class="la la-ellipsis-h"></i></small>
									    </div>
									    <div class="divider"></div>
									    <div class="container-fluid">
									    	<div class="row mt-1 mb-1">
									    		<div class="col-lg-12">
									    				<form action="{% url 'vote:user-vote'%}" method="POST" class="vote-form">
									    					{% csrf_token %}
									    					{{vote_form}}
									    				</form>
									    				<span class="comment-action">
									    					<i class="la la-comments"></i>
									    					Comments
									    				</span>
									    				<!-- <span>
									    					Share
									    				</span> -->
									    		</div>
									    	</div>
									    	{% if is_auth %}
									    	<div class="row mt-3 mb-3">
									    		<div class="col-lg-2 col-md-2 col-sm-2">
									    			{% if request.user.profile.pic %}
									    			<img src="{{request.user.profile.pic_url}}" class="rsp-avatar" alt=""/>
									    			{% else %}
									    			<img src="{% static 'img/avatar.jpg' %}" alt="" class="rsp-avatar" />
									    			{% endif %}
									    		</div>
									    		<div class="col-lg-10 col-md-10 col-sm-10">
										    		<form action="{% url 'comment:comment-post' %}" method="POST" class="comment-form">
										    			{% csrf_token %}
										    			<input type="text" name="comment" placeholder="add a comment..." class="comment-input">
										    			<input type="hidden" name="answer-comment" value="{{q.most_upvote_answer.id}}">
										    			<!-- loader -->
										    			<span class="loader-span">posting...</span>
										    		</form>
									    		</div>
									    	</div>
									    	{% endif %}
									    </div>
								  </div>
								  {% endfor %}
						  {% endif %}
						<!-- card close here -->