config/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path,include
from django.views import defaults as default_views

from . import views

urlpatterns = [
    path('',views.welcome_to_inqoire,name='index'),
    path('account/',include('inqoire.account.urls',namespace='account')),
    path('comment/',include('inqoire.comment.urls',namespace='comment')),
    path('answer/',include('inqoire.answer.urls',namespace='answer')),
    path('question/',include('inqoire.question.urls',namespace='question')),
    path('users/',include('inqoire.users.urls',namespace='users')),
    path('vote/',include('inqoire.vote.urls',namespace='vote')),
    path('connection/',include('inqoire.connection.urls',namespace='connection')),
    path('admin/', admin.site.urls),# change url in production. `SECURITY` reasons.
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    
    # Test Dev. Error Pages
    urlpatterns += [
        path('400/', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        path('403/', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        path('404/', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        path('500/', default_views.server_error),
    ]

inqoire/connection/urls.py
from django.urls import path
from .import views


app_name = 'connection'

urlpatterns = [
    path('switch-connection/',views.switch_connection,name='connection-switch'),
]

inqoire/users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
	path('inQ/<str:username>/',views.view_by_user,name='user-view'),
	path('inQ/edit/<str:username>/',views.edit_profile,name='edit-profile'),
    
]

inqoire/users/models.py
# @purpose - App handles inQoire User, Profile ... avatar,gravatar,dashboard

from django.utils import timezone
from django.conf import settings
from django.urls import reverse
from django.db.models import F

from django.contrib.auth.models import AbstractUser
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import BadHeaderError,send_mail
from django.db import models

from inqoire.utils.functions import activation_token,date_expired
# from inqoire.connection.models import Connection
from inqoire.account import build_absolute_uri
from inqoire.utils import helpers



class User(AbstractUser):
    ''' User Model.
    if actived_on is not None.
    Then based on when its acitvate ,set expire date to use site. 

    '''
    score   		            = models.PositiveSmallIntegerField(default=0,blank=True,null=True)
    phone_number                = models.CharField(max_length=16,blank=False,null=True,unique=True)
    joined_from_ip              = models.GenericIPAddressField(blank=True,null=True)
    last_seen_ip                = models.GenericIPAddressField(blank=True,null=True)
    activated_on                = models.DateTimeField(blank=True,null=True) # date account was activated after mail was sent.
    free_subscription_ends_on   = models.DateTimeField(blank=True,null=True) # set 1 month of site use,like its done on medium.com
 
    # is_subscriber     = models.BooleanField(default=False) # for payed users.

    def __str__(self):
        return self.username


    @property
    def full_name(self):
        if self.first_name and self.last_name:
            return self.last_name +' '+self.first_name
        return self.username

    @property
    def user_username(self):
        return "{0}@inQ".format(str(self.username))


    @property
    def questions_count(self):
        return self.questions.count


    @property
    def free_subscription_ended(self):
        if not self.free_subscription_ends_on is None:
            return bool(self.free_subscription_ends_on < timezone.now())


    def get_absolute_url(self):
        return reverse('users:user-view',args=[str(self.username)])


    @property
    def url(self):
        # i kind of like shortcuts :)
        return self.get_absolute_url()


    @property
    def people_user_is_connected_to(self):
        return [connection.from_user for connection in self.from_user.all()]


    @property
    def people_connected_to_count(self):
        # returns a count of all the people i have connected to,but not connected to me.
        # users connected to us are not regarded as a connection. (just wants things that way.)
        return self.to_user.count()
    



    
    
    
class Profile(models.Model):
    '''
    user profile.
    @attr
    +owner
    +profession
    +pic
    +bio


    '''
    owner           = models.OneToOneField(to=settings.AUTH_USER_MODEL,
                                            related_name='profile',
                                            on_delete=models.CASCADE)
    pic             = models.ImageField(upload_to=helpers.dp_upload_loc,blank=True,null=True)
    bio             = models.TextField(max_length=150,blank=True,null=True,default='This project was built as my #2 exercise with Python.')
    profession      = models.CharField(max_length=150,blank=True,null=True)
    gender          = models.CharField(max_length=6,blank=True,null=True)

    created         = models.DateTimeField(auto_now_add=True)
    updated         = models.DateTimeField(auto_now=True)

    class Meta:
        ordering       = ('-created',)
        verbose_name   = 'Profile'
        verbose_name_plural = 'Profiles'


    def __str__(self):
        return str(self.owner.username)



    @property
    def pic_url(self):
        if self.pic:
            return self.pic.url
        return
    






class Activation(models.Model):
    ''' Activation Model.'''
    token       = models.CharField(max_length=250,unique=True,blank=True,null=True)
    user        = models.ForeignKey(to=User,on_delete=models.CASCADE)
    expired     = models.DateTimeField(blank=True,null=True)
    is_sent     = models.BooleanField(default=False)

    created     = models.DateTimeField(auto_now_add=True)


    class Meta:
        verbose_name = 'Activation'
        verbose_name_plural = 'Activations'


    def __str__(self):
        return '{0}'.format(self.token)



    @classmethod
    def create_activation_token(cls,user):
        # creates and returns activation object
        return cls.objects.create(token=activation_token(),
                                  user=user,
                                  expired=date_expired(),
                                  is_sent=True)


    def send(self,request = None):
        '''@method - send activation email'''
        if request is not None:
            domain = get_current_site(request).domain

            # get activation route full path.
            full_activation_url = build_absolute_uri(
                reverse(
                    'account:validate-token',
                    kwargs={'token':self.token}
                ),
                request
            )
            # print(full_activation_url)
            subject = 'Account Activation Confirmation.'
            message = "To activate {0} account for email {1} click on this link {2}".format(domain,
                self.user.email,
                full_activation_url)
            from_email = settings.DEFAULT_FROM_EMAIL
            to_email = self.user.email

            try:
                send_mail(subject,message,from_email,[to_email],fail_silently=True)
                # print('mail sent')
            except BadHeaderError:
                pass



    def is_expired(self):
        return self.expired < timezone.now()

inqoire/users/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth.decorators import login_required
from django.template.response import TemplateResponse
from django.http import HttpResponse,Http404

from inqoire.utils.decorators import owner_required
from inqoire.users.models import User as inQoireUser


# view for a inQoire user.
def view_by_user(request,**kwargs):
	user = get_object_or_404(inQoireUser,username__iexact=kwargs['username'].strip())
	return TemplateResponse(request,'user/profile.html',{'username':kwargs['username'],'user_obj':user})


@login_required
@owner_required
def edit_profile(request,username):
	return HttpResponse("Edit profile")

templates/user/profile.html
{% extends '_layout.html' %}
{% load static %}

<!-- css -->
{% block css %}

.answer-file-resp{
	height: 55vh;
    display: block;
    width: 100%;
    max-width: 100%;
}

.answer-input{
	width: 100%;
    height: 2.5em;
    border-radius: 6px;
    outline: none;
    border: 1px solid #e3dcdc;
    padding: .111em 1em;
    color: #9b9a9a;
    font-size: 16px;
    font-weight: 600;
}

.nav-link .la-search{
	display:none !important;
}

.edit-href{
	font-size: 19px;
    margin: 4px 3px 4px 0;
    color: #9c9c9c;
}

{% endblock %}
<!-- /css -->

<!-- navigation -->
{% block nav %}
	{% include 'partials/_nav.html' %}
{% endblock %}
<!-- /navigation -->


{% block content %}
	<section class="container content-container">
		<section class="row" style="margin-top: 8em;">
			<!-- <section class="col-lg-4 shadow-sm "> -->
				<!-- card 1 -->
				<div class="card col-lg-3 col-md-3 shadow-sm aside-card">
					  {% if user_obj.profile.pic %}
					  <img src="{{user_obj.profile.pic_url}}" class="avatar-aside" alt="...">
					  {% else %}
					  <img src="{% static 'img/avatar.jpg' %}" class="card-img-top avatar-aside" alt="...">
					  {% endif %}
					  <div class="card-body card-body-height card-height-profile text-center">
					    <h5 class="card-title card-title-h5"><a href="{{request.user_obj.url}}">{{ user_obj.full_name }}</a></h5>
					    <h6 class="card-title">
					    	<a href="{{user_obj.url}}">{{user_obj.user_username}}</a>
					    </h6>
					    <!-- Test -->
					    <!-- /Test -->
					    {% if is_auth %}
					     {% ifnotequal request.user user_obj %}
						    <form action="{% url 'connection:connection-switch' %}" method="POST" class="connection-form">
								{% csrf_token %}
								<input type="submit" class="btn btn-outline-primary follow-btn {% if request.user in user_obj.people_user_is_connected_to %}is-connected{% endif %}" value="
								{% if request.user in user_obj.people_user_is_connected_to %}Connected{% else %}Connect{% endif %}" name='follow_btn'/>
								<input type="hidden" name="from_user" value="{{request.user.username}}">
								<input type="hidden" name="to_user" value="{{user_obj.username}}">
							</form>
					     {% endifnotequal %}
					    {% endif %}
					  </div>
					  <ul class="list-group list-group-flush clear-fix">
					    <li class="list-group-item">Contribution{{user_obj.contribs.count|pluralize}}<span class="badge badge-light float-right user-contrib-count">{{user_obj.contribs.count}}</span>
					    </li>
					    <li class="list-group-item">Question{{user_obj.questions.count|pluralize}}<span class="badge badge-light float-right user-question-count">{{user_obj.questions.count}}</span>
					    </li>
					    <li class="list-group-item">Connection{{user_obj.people_connected_to_count|pluralize}}<span class="badge badge-light float-right connect-count">{{user_obj.people_connected_to_count}}</span>
					    </li>
					  </ul>
					  <!-- 	{% ifequal request.user user_obj %}
					  		<section class="col-lg-12">
					  			<a href="{% url 'users:edit-profile' user_obj.username %}" title="edit profile" class="edit-href"><i class="la la-edit"></i></a>
					  		</section>
					  	{% endifequal %} -->
				</div>
				<!-- / card 1 -->
			<!-- </section> -->
			<section class="col-lg-9 col-md-9 shadow-sm right-col-sec">
				<section class="col-lg-12">
				  <section class="row section-box-wrap">
				  	<section class="col-lg-3 col-md-3 section-box count-fig-active">
				  		<p class="count-fig">{{user_obj.people_connected_to_count}}</p>
				  		<span>Connection{{user_obj.people_connected_to_count|pluralize}}</span>
				  	</section>
				  	<section class="col-lg-3 col-md-3 section-box">
				  		<p class="count-fig">{{user_obj.questions.count}}</p>
				  		<span>Question{{user_obj.questions.count|pluralize}} Asked</span>
				  	</section>
				  	<section class="col-lg-3 section-box">
				  		<p class="count-fig">{{user_obj.contribs.count}}</p>
				  		<span>Contribution{{user_obj.contribs.count|pluralize}}</span>
				  	</section>
				  	<section class="col-lg-3 section-box">
				  		<p class="count-fig">{{user_obj.comment_by.count}}</p>
				  		<span>Comment{{user_obj.comment_by.count|pluralize}}</span>
				  	</section>
				  </section>
				</section>

				<!-- question-answer-card sec-->
				<section class="col-lg-12">
					<section class="row">
						  <section class="col-lg-12">
						  	<section class="row">
						  		<section class="col-lg-5">
						  			Left
						  		</section>
						  		<section class="col-lg-7">

						  			Right
						  		</section>
						  	</section>
						  </section>
					</section>
				</section>
				<!-- /question-answer-card sec-->
			</section>
		</section>
	</section>
{% endblock %}